title: My Jekyll Site
email: wizzardsk@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  A simple and beautiful website built with Jekyll and GitHub Pages.
baseurl: "/APF_-_MP-1000" # the subpath of your site, e.g. /blog, or leave empty if not applicable
url: "https://wizzardsk.github.io" # the base hostname & protocol for your site
twitter_username: wizzardsk
github_username:  wizzardsk

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
